import axios from 'axios'

// La URL debe venir de la configuración del usuario
let ANKI_CONNECT_URL = 'http://127.0.0.1:8765'

// Función para establecer la URL de AnkiConnect
export function setAnkiConnectUrl(url: string) {
  ANKI_CONNECT_URL = url
}

export async function ankiInvoke(
  action: string,
  params: Record<string, unknown>
) {
  const request: AnkiRequest = {
    action,
    version: 6,
    params,
  }

  try {
    const { data } = await axios.post(ANKI_CONNECT_URL, request)
    if (data.error) {
      throw new Error(data.error)
    }
    return data.result
  } catch (error) {
    console.error('AnkiConnect Error: ', error)
    throw error
  }
}

export async function createDeck(deckName: string) {
  return ankiInvoke('createDeck', { deck: deckName })
}

export async function addCard(cardPayload: CardPayload) {
  const { deckName, front, back, audioPath, audioFilename } = cardPayload

  const card: AnkiCard = {
    deckName: deckName,
    modelName: 'Basic',
    fields: {
      Front: front,
      Back: back,
    },
    options: {
      allowsDuplicate: false,
    },
    tags: ['generated by anki card creator'],
  }

  if (audioPath && audioFilename) {
    card.audio = {
      path: audioPath,
      filename: audioFilename,
      fields: ['Back'],
    }
  }

  return ankiInvoke('addCard', { card })
}
